# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core


trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'
  myproject: 'MinimalAPIsMovies/MinimalAPIsMovies.csproj'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 8'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Compiling the project'
- task: CmdLine@2
  displayName: 'Installing EF Core CLI'
  inputs:
    script: 'dotnet tool install --global dotnet-ef'
- task: CmdLine@2
  displayName: 'Generating the migration script'
  inputs:
    script: 'dotnet ef migrations script -i -o $(Build.ArtifactStagingDirectory)\migrate.sql --project $(myproject)'
- task: DotNetCoreCLI@2
  displayName: 'Creating the final files of our project'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: $(myproject)
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --runtime win-x86'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: 'publishing the artifacts'
